name: Pipeline de Release - Blue/Green

on:
  push:
    tags: ['v*']

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_tag: ${{ github.ref_name }}
      docker_username: fabian777omg
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy-blue:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: blue
      image_tag: ${{ github.ref_name }}
      docker_username: fabian777omg
    secrets:
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

  switch-traffic:
    needs: deploy-blue
    runs-on: ubuntu-latest
    steps:
      - name: Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Validacion de salud Blue
        run: |
          kubectl wait --for=condition=ready pod \
            -l app=api-cliente,version=blue \
            --timeout=60s

      - name: Switch trafico a Blue
        run: |
          kubectl patch service api-cliente-service \
            -p '{"spec":{"selector":{"app":"api-cliente","version":"blue"}}}'
          echo "Trafico apuntando a Blue"
          kubectl get service api-cliente-service