name: Pipeline de Validacion
on:
  push:
    branches-ignore: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutando Test
        run: echo "Validacion exitosa para TechMaster LTDA"